name: Publish to Test PyPI

on:
  release:
    types: [prereleased]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.x'

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: 'latest'
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}

    - name: Install dependencies
      run: |
        poetry install --no-dev  # Install only the main dependencies

    - name: Build package
      run: poetry build

    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      run: poetry publish --build
