name: Publish to Test PyPI

on:
  push:
    tags:
      - '*-dev'  # Triggers the action on tags containing '-dev'

jobs:
  publish-to-testpypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: 'latest' 

    - name: Install dependencies
      run: poetry install

    - name: Build the package
      run: poetry build

    - name: Publish to Test PyPI
      env:
        POETRY_PYPI_TOKEN_TEST_PYPI: ${{ secrets.ORG_PYPI__API_TOKEN }}
      run: poetry publish -r test-pypi --build

