name: Publish to Test PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.x'

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: '1.8.3'

    - name: Install dependencies
      run: |
        poetry install --no-dev

    - name: Build package
      run: poetry build
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.ORG_PYPI__API_TOKEN }}

    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.ORG_PYPI__API_TOKEN }}
      run: poetry publish --build
